# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "tower" do |tower|
    tower.vm.box = "ansible/tower"
    tower.vm.network "private_network", ip: "192.168.50.10"
    tower.vm.hostname = "tower"
    tower.vm.network "forwarded_port", guest: 80, host: 8010
  end
  config.vm.define "web1" do |web1|
    web1.vm.box = "generic/fedora31"
    web1.vm.network "private_network", ip: "192.168.50.11"
    web1.vm.hostname = "web1"
    web1.vm.network "forwarded_port", guest: 80, host: 8011
  end
  config.vm.define "web2" do |web2|
    web2.vm.box = "generic/fedora31"
    web2.vm.network "private_network", ip: "192.168.50.12"
    web2.vm.hostname = "web2"
    web2.vm.network "forwarded_port", guest: 80, host: 8012
  end
  config.vm.provision "ansible" do |ansible|
   ansible.groups = {
      "tower" => ["tower"],
     "lab" => ["web1","web2"]
    }
    ansible.verbose = "v"
    ansible.playbook = "server_access.yml"
  end
end